decabonify_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

products/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=254)
    slug = models.CharField(max_length=254, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_slug(self):
        return self.slug

       
class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(
        max_length=2000, null=True, blank=True)
    image = models.ImageField(
        null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        slug = [(c.id, c.get_slug()) for c in categories]

        self.fields['category'].choices = slug
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category
from .forms import ProductForm

# Create your views here.

def all_products(request):
    """Sort all solutions and search queries"""

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None


    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Untracked search criteria, enter field!")
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view showing all solution products, sort and search quiries"""

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    if not request.user.is_superuser:
        messages.error(request, "Sorry, you cannot access this page if you not owner.")
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Welldone! Product added successfully.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Not able to add product. Check your form validity.')
    else:
        form = ProductForm()

    template = "products/add_product.html"
    context = {
        "form": form,
    }
    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    if not request.user.is_superuser:
        messages.error(request, "Sorry, you cannot access this page if you not owner.")
        return redirect(reverse('home')) 

    """ Update solutions provided """
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Great! Product updated.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to update product. Check your form.')
    else: 
        form = ProductForm(instance=product)
        messages.info(request, f'Editing solution {product.name}')

    template = "products/edit_product.html"
    context = {
        "form": form,
        "product": product,
    }
    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    if not request.user.is_superuser:
        messages.error(request, "Sorry, you cannot access this page if you not owner.")
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    product.delete()
    messages.success(request, f'{product.name} successfully deleted')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}
{% load wishlist_tools %}

{% block extra_css %}
{% endblock %}

{% block extra_title %}Add Product{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}
<h2 class="page-title text-center uppercase product-form-wrap">Manage Solutions</h2>
<h3 class="text-center">Add Solution</h3>
<hr>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-3" enctype="multipart/form-data">
            {% csrf_token %}
                    {% for field in form %}

                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            <img src="#" style="display:none;height:100px;width:100px;padding:10px;" id="uploadedImage" />
                            {{ field }}
                        {% endif %}
                    {% endfor %}
            <div class="text-right">
                <a class=" btn btn-outline-success ml-4" href="{%  url 'products' %}"><i class="fas fa-window-close mr-1"></i>Cancel</a>
                <button class="btn btn-success" type="Submit"><i class="fas fa-plus-square mr-1"></i>Add Product</button>
            </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block postload_js %}
<script>
$(document).ready(function(){
    console.log("document ready");
    $('#id_image').on('change',function(){
        console.log('image changed');
        var file = document.getElementById('id_image').files[0]
        displayImageOnChange(file);
    });
});

function displayImageOnChange(file){
    var reader = new FileReader();
    reader.onload = function(e){
        var displayimage = document.getElementById('uploadedImage');
        console.log(e.target.result);
        displayimage.src = e.target.result;
        $('#uploadedImage').css('display','block');
    }
    reader.readAsDataURL(file);
}

</script>

{% endblock %}

products/templates/products/edit-product.html
{% extends "base.html" %}
{% load static %}
{% load wishlist_tools %}

{% block extra_css %}
{% endblock %}

{% block extra_title %}Edit Product{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}
<h2 class="page-title text-center uppercase">Manage Solutions</h2>
<h3 class="text-center">Edit Solutions</h3>
<hr>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit-product' product_id %}" class="form mb-3" enctype="multipart/form-data">
            {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
            <div class="text-right">
                <a class=" btn btn-outline-dark" href="{%  url 'products' %}"><i class="fas fa-window-close mr-1"></i>Cancel</a>
                <button class="btn btn-success" type="Submit"><i class="fas fa-retweet"></i> Edit Solution</button>
            </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}
{% load wishlist_tools %}

{% block extra_css %}
{% endblock %}

{% block extra_title %}Edit Product{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}
<h2 class="page-title text-center uppercase product-form-wrap">Manage Solutions</h2>
<h3 class="text-center">Edit Solutions</h3>
<hr>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-3" enctype="multipart/form-data">
            {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            <img src="/MEDIA_URL/{{field.value}}" style="display:block;height:100px;width:100px;padding:10px;" id="uploadedImage" />
                            {{ field }}
                        {% endif %}
                    {% endfor %}
            <div class="text-right">
                <a class=" btn btn-outline-success" href="{%  url 'products' %}"><i class="fas fa-window-close mr-1"></i>Cancel</a>
                <button class="btn btn-success" type="Submit"><i class="fas fa-retweet"></i> Edit Solution</button>
            </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block postload_js %}
<script>
$(document).ready(function(){
    console.log("document ready");
    $('#id_image').on('change',function(){
        console.log('image changed');
        var file = document.getElementById('id_image').files[0]
        displayImageOnChange(file);
    });
});

function displayImageOnChange(file){
    var reader = new FileReader();
    reader.onload = function(e){
        var displayimage = document.getElementById('uploadedImage');
        console.log(e.target.result);
        displayimage.src = e.target.result;
        $('#uploadedImage').css('display','block');
    }
    reader.readAsDataURL(file);
}



</script>

{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
    <div class="container-fluid pt-5 detail-info">
        <div class="col-12 d-flex justify-content-center detail-card">
            <div class="col-md-5 col-lg-5 order-md-first bg-0 my-4">
                <img class="img-fluid mx-auto d-block"  alt="responsive product img"
                    src="{{ product.image.url }}" target="_blank">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <div class="product-details-container mb-5 mt-md-5">
                    <h3 class="mb-3 detail-name">{{ product.name }}</h3>
                    <div class="border-0">
                        <div class="col">
                            <div class="row">
                                <div class="col-6 text-uppercase ml-0">Solution Cost</div>
                                <div class="col-6 text-end text-muted">
                                    <span class="h4 fw-fold">
                                        ${{ product.price }}
                                    </span>
                                </div>
                               
                                {% if product.rating %}
                                    <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                                {% else %}
                                    <small class="text-muted mr-3">No Rating</small>
                                {% endif %}
                                {% if request.user.is_superuser %}
                                    <small class="ml-3">
                                        <a href="{% url 'edit_product' product.id %}" class="text-success">Edit</a> |
                                        <a class="text-basket" href="{% url 'delete_product' product.id %}">Delete</a>
                                    </small>
                                {% endif %}

                            </div>
                             <p class="mt-2">{{ product.description|slice:"354" }}...</p>
                        </div>
                            
                        </div>
                    </div>

                    <form class="form" action="{% url 'add_to_wishlist' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-col">
                            <div class="col-12 mt-0">
                                <label for="select"><strong>Qty</strong></label>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="minus-qty btn btn-success rounded-0" 
                                                data-item_id="{{ product.id }}" id="minus-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_add" type="number" name="quantity" 
                                            value="1" min="1" max="99" data-item_id="{{ product.id }}" 
                                            id="id_qty_{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="plus-qty btn btn-success rounded-0"
                                                data-item_id="{{ product.id }}" id="plus-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-12">
                                <a href="{% url 'products' %}" class="btn btn-outline-success rounded-0 mt-0">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Continue Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-success rounded-0 text-uppercase" value="Add to Bucket">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>             
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/qty_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
    {% comment %} start product intro {% endcomment %}
        <section class="jumbotron text-center py-5 allproduct-info">
            <div class="container">
            <h1 class="text-dark py-5">Solutions available</h1>
            <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
            <p>
                <a href="{% url 'account_signup' %}" class="btn btn-success my-2">Register</a>
                <a href="{% url 'account_login' %}" class="btn btn-secondary my-2">Login</a>
            </p>
            </div>
        </section>


    {% comment %} start solution list {% endcomment %}
        <section class="my-3">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col text-center mt-3">
                            <h2 class="mb-5 mt-5 text-success"><strong>Tailor-made Solutions</strong></h2>
                            {% for c in current_categories %}
                                <a class="solution-category-badge text-decoration-none" href="{% url 'products' %}?category={{ c.name }}">
                                    <span class="p-2 mt-2 badge badge-white text-dark rounded-0 border border-dark">{{ c.sku }}</span>
                                </a>
                            {% endfor %}
                            <hr class="container w-50 mb-3">
                        </div>
                    </div>
                </div>
            
                <div class="row">
                    <div class="product-container col-10 offset-1">
                        <div class="row mt-1 mb-2">
                            <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                                <div class="sort-container w-50">
                                    <select id="sort-finder" class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                        <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                                        <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                                        <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                                        <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                                        <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                                        <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                                        <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                                        <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)</option>
                                        <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-12 col-md-6 order-md-first">
                                <p class="text-muted mt-3 text-center text-md-left">
                                    {% if search_term or current_categories or current_sorting != 'None_None' %}
                                        <span class="small"><a href="{% url 'products' %}">Products Home</a> | </span>
                                    {% endif %}
                                    {{ products|length }} Products{% if search_term %} filtered with <strong>"{{ search_term }}"</strong>{% endif %}
                                </p>
                            </div>
                        </div>
                            <div class="row">
                                {% if products.count == 0 %}
                                    <div class="text-center no-match">
                                        <h2>No matching items</h2>
                                    </div>
                                {% else %}
                                {% for product in products %}
                                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                                        <div class="card h-100 border-0 shadow mb-5 bg-white rounded ">

                                            <a href="{% url 'product_detail' product.id %}">
                                                {% if product.image %}
                                                <img class="card-img-top img-fluid img-responsive" loading="lazy" src="{{product.image.url}}" alt="{{ product.name }}">

                                                {% else %}
                                                <img class="card-img-top img-fluid img-responsive" loading="lazy" src="https://youmatter.world/app/uploads/sites/2/2018/10/climate-change-definition-meaning.jpg" alt="{{ product.name }}">

                                                {% endif %}
                                            </a>
                                            
                                            <div class="card-body pb-0">
                                                <h4 class="card-title text-success mb-3">{{ product.name|upper }}</h4>
                                                <p class="mb-0 text-truncate font-weight-light text-muted">{{ product.description }}</p>
                                            </div>

                                            <div class="card-footer bg-white pt-0 border-0 text-left">
                                                <div class="row">
                                                    <div class="col">
                                                        <p class="mb-0 text-left font-weight-bold">&euro;{{ product.price }}</p>
                                                        {% if product.rating %}
                                                            <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                                                        {% else %}
                                                            <small class="text-muted">Rating : None</small>
                                                        {% endif %}
                                                        {% if request.user.is_superuser %}
                                                            <small class="ml-3">
                                                                <a href="{% url 'edit_product' product.id %}">Edit</a> |
                                                                <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                                                            </small>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="d-flex justify-content-center py-4">
                                                        <a href="{% url 'product_detail' product.id %}" class="btn btn-success text-uppercase font-weight-bold">View More</a>
                                            </div>

                                        </div>
                                    </div>
                                {% if forloop.counter|divisibleby:1 %}
                                    <div class="col-12 d-sm-none mb-5">
                                        <hr>
                                    </div>
                                {% endif %}                        
                                {% if forloop.counter|divisibleby:2 %}
                                    <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                        <hr>
                                    </div>
                                {% endif %}
                                {% if forloop.counter|divisibleby:3 %}
                                    <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                        <hr>
                                    </div>
                                {% endif %}
                                {% if forloop.counter|divisibleby:4 %}
                                    <div class="col-12 d-none d-xl-block mb-5">
                                        <hr>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="scroll-btn shadow-sm rounded-0 border border-black">
        <a class="d-flex h-100" id="scroll-link" >
            <i class="fas fa-arrow-up text-dark mx-auto my-auto"></i>
        </a>	
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <!-----Scroll to top when arrow up clicked BEGIN--->
    <script type="text/javascript">
        $(window).scroll(function() {
            var height = $(window).scrollTop();
            if (height > 100) {
                $('#scroll-link').fadeIn();
            } else {
                $('#scroll-link').fadeOut();
            }
        });
        $(document).ready(function() {
            $("#scroll-link").click(function(event) {
                event.preventDefault();
                $("html, body").animate({ scrollTop: 0 }, "slow");
                return false;
            });

        });
	</script>
    <!----Scroll to top when arrow up clicked END---->

    
    <script type="text/javascript">
        $('#sort-finder').change(function() {
            var selector = $(this);
            var currentUrl = new URL(window.location);

            var selectedVal = selector.val();
            if(selectedVal != "reset"){
                var sort = selectedVal.split("_")[0];
                var direction = selectedVal.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
    </script>
{% endblock %}